application: py-editor
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static/css
  static_dir: static/css
- url: /static/data
  static_dir: static/data
- url: /static/html
  static_dir: static/html
- url: /static/js
  static_dir: static/js
- url: /.*
  script: main.app
  
libraries:
- name: jinja2
  version: latest